export const teamCards = [
  {
    id: "1",
    image: "/AdrianiPutri.png",
    name: "Adriani Putri",
    departement: "Chief Marketing Officer",
    ig: "https://www.instagram.com/adrianiputri/",
    fb: "https://www.facebook.com/adrianiputri17/",
    linkedIn: "https://www.linkedin.com/in/adrianiputri/",
    titleIg: "adrianiputri",
    titleFb: "adrianiputri17",
    titleLinkedIn: "adrianiputri",
  },
  {
    id: "2",
    image: "/KaniaCinari.png",
    name: "Kania Cinari",
    departement: "Chief Operating Officer",
    ig: "https://www.instagram.com/kaniacinari/",
    fb: "https://www.facebook.com/kania.sinamo",
    linkedIn: "https://www.linkedin.com/in/kania-cinari-h-sinamo-a07035131/",
    titleIg: "kaniacinari",
    titleFb: "kania.sinamo",
    titleLinkedIn: "kania-cinari-h-sinamo-a07035131",
  },
  {
    id: "3",
    image: "/Avianita.png",
    name: "Avianita Rahmawati",
    departement: "Chief Financial Officer",
    ig: "https://www.instagram.com/avooi/",
    fb: "https://www.facebook.com/avooi",
    linkedIn: "https://www.linkedin.com/in/avianita-rahmawati/",
    titleIg: "avooi",
    titleFb: "avooi",
    titleLinkedIn: "avianita-rahmawati",
  },
];
